spring:
  application:
    name: summy-api
  profiles:
    active: ${ACTIVE_PROFILE:local}
  datasource:
    url: jdbc:mariadb://database-1.cnyqy8snc0sl.ap-northeast-2.rds.amazonaws.com:3306/database-1
    username: admin
    password: ${DB_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost:9092/./testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY:}
    url: https://api.openai.com/v1

# 서버 포트 설정
server:
  port: 8080