# 공통 설정 (모든 환경에 적용됩니다)
spring:
  application:
    name: summy-api  # 애플리케이션 이름 설정
  profiles:
    active: ${ACTIVE_PROFILE:local}  # 활성 프로파일 설정, 기본값은 local
  datasource:
    # 프로덕션 데이터베이스 설정
    url: jdbc:mariadb://database-1.cnyqy8snc0sl.ap-northeast-2.rds.amazonaws.com:3306/database-1
    username: admin
    password: ${DB_PASSWORD:}  # 환경 변수에서 DB 비밀번호 로드
    driver-class-name: org.mariadb.jdbc.Driver  # MariaDB 드라이버 클래스
  jpa:
    hibernate:
      ddl-auto: none  # 스키마 자동 생성 비활성화 (프로덕션에서는 none 권장)
    open-in-view: false  # OSIV 패턴 비활성화 (성능 최적화)
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅
        show_sql: true  # SQL 쿼리 로깅
        use_sql_comments: true  # SQL 주석 활성화
        dialect: org.hibernate.dialect.MariaDBDialect  # MariaDB 방언 설정

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY:}  # 환경 변수에서 OpenAI API 키 로드
    url: https://api.openai.com/v1  # OpenAI API 엔드포인트

# 서버 포트 설정
server:
  port: 8080  # 애플리케이션 서버 포트