# API 모듈 공통 설정 (모든 환경에 적용됩니다)
spring:
  application:
    name: summy-api  # 애플리케이션 이름 설정
  profiles:
    active: ${ACTIVE_PROFILE:local}  # 활성 프로파일 설정, 기본값은 local

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY:}  # 환경 변수에서 OpenAI API 키 로드
    url: https://api.openai.com/v1  # OpenAI API 엔드포인트

# 서버 포트 설정
server:
  port: 8080  # 애플리케이션 서버 포트

# 외부 API 설정
external:
  api:
    base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    openai:
      api-key: ${OPENAI_API_KEY:}  # 환경 변수에서 API 키 로드
      model: ${OPENAI_MODEL:gpt-3.5-turbo}  # 환경 변수에서 모델명 로드